### ISSUE TITLE
Support for accept_insiderEula (NextMinor/NextMajor)

### ISSUE THREAD

**Issue by Arthurvdv** [tfenster/bcartifacturl-proxy#1]
To improve our Azure DevOps pipelines we're look into implementing the bcartifacturl-proxy and it looks promising at the moment!

Can we also use this for the Next Minor and Next Major artifacts?

```PS
Get-BCArtifactUrl -type Sandbox -country BASE -select NextMajor -accept_insiderEula

Invoke-WebRequest 'https://bca-url-proxy.azurewebsites.net/bca-url/Sandbox/BASE?select=NextMajor&DoNotRedirect=true'
```

I've try'ed the example above, where the bcartifacturl-proxy returns a HTTP 400 it seems 🤔
Am I doing something wrong or could it be that at this moment only the sasToken is implemented?

https://github.com/tfenster/bcartifacturl-proxy/blob/be8751dd671609dbe1b714c209cea3dc69ad91fa/GetUrl.cs#L58

**Comment by tfenster** [comment]
@Arthurvdv Great input thanks. And indeed, that param is currently missing. I'll try to take a look at that, but if you wan't, also feel free to create a PR adding it

**Comment by Arthurvdv** [comment]
Challenge accepted 😅

I’m going to try this in the upcoming days and if everything goes well, I will create an PR.

**Comment by tfenster** [comment]
@Arthurvdv I have merged the PR and deployed it to the backend. So now I can

```
PWSH C:\Users\tfenster> Invoke-WebRequest 'https://bca-url-proxy.azurewebsites.net/bca-url/Sandbox/BASE?select=NextMajor&DoNotRedirect=true'

StatusCode        : 200
StatusDescription : OK
Content           : https://bcinsider.azureedge.net/sandbox/24.0.16410.17513/base
```

Does that work as expected for you as well?

**Comment by Arthurvdv** [comment]
![image](https://github.com/tfenster/bcartifacturl-proxy/assets/44637996/8460d7be-6c94-440a-bbe8-4e1a77b351bc)

It works beautifully as expected and now also integrated with our ADO pipelines 🤗

And thank you for accepting the PR!

**Comment by tfenster** [comment]
@Arthurvdv I wrote a little blog post about this PR (https://tobiasfenster.io/getting-bc-insider-artifacts-without-powershell-or-a-token-and-the-bc-community-is-great) and shared it on X and LinkedIn, tagging you always. Please let me know if you feel misrepresented in any way or want me to remove your name there. As this PR is out in the open, I couldn't imagine why you would want that, but if it is the case, please let me know

**Comment by Arthurvdv** [comment]
@tfenster, Thank you for reaching out, and it's no problem you've tagged me.

I was great working on this PR and while contributing to the community also gaining more experience working with Azure Functions. And the icing on the cake with an honor to be personally mentioned by an Microsoft MVP 🤗
